# Generated by Django 6.0.5 on 2026-06-11 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="chaiVariety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="chai_variety_images/")),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("black", "Black"),
                            ("green", "Green"),
                            ("herbal", "Herbal"),
                            ("oolong", "Oolong"),
                            ("white", "White"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
